version: "2"

services:
  ros2_workbench:
    container_name: workbench
    build:
      context: .
    shm_size: 2gb
    ports:
      - "6080:80"
    volumes:
     - './data:/home/ubuntu/Desktop/works'